{% set version = "3.6.1" %}

# Recipe for a static libarchive with support for the features needed for
# conda-package-handling (bzip2, zlib, zstd).
# This is not a general purpose libarchive

package:
  name: _libarchive_static_for_cph
  version: {{ version }}

source:
  url: https://github.com/libarchive/libarchive/releases/download/v{{ version }}/libarchive-{{ version }}.tar.gz
  sha256: c676146577d989189940f1959d9e3980d28513d74eedfbc6b7f15ea45fe54ee2
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    - patches/0009-CMake-Force-Multi-threaded-DLL-runtime.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf    # [unix]
    - automake    # [unix]
    - libtool     # [unix]
    - pkg-config  # [unix]
    - cmake       # [win]
    - make        # [unix]
  host:
    - bzip2
    - libiconv    # [osx]
    - zlib
    - zstd                   # [not unix]
    - zstd-static            # [unix]    

test:
  commands:
    # Verify headers are in place.
    - test -f "${PREFIX}/include/archive.h"                              # [unix]
    - test -f "${PREFIX}/include/archive_entry.h"                        # [unix]
    - if not exist %PREFIX%\Library\include\archive.h exit /b 1         # [win]
    - if not exist %PREFIX%\Library\include\archive_entry.h exit /b 1   # [win]

    # Verify libraries are in place.
    - test -f "${PREFIX}/lib/libarchive.a"                               # [unix]
    - test -f "${PREFIX}/lib/libarchive_and_deps.a"                      # [unix]
    - if not exist %PREFIX%\Library\lib\archive_static.lib exit /b 1    # [win]
    - if not exist %PREFIX%\Library\lib\archive_and_deps.lib exit /b 1  # [win]
    - if not exist %LIBRARY_LIB%\zstd_static.lib  exit 1       # [win]
    - if not exist %LIBRARY_LIB%\bzip2_static.lib  exit 1      # [win]
    - if not exist %LIBRARY_LIB%\zlibstatic.lib  exit 1        # [win]

about:
  home: http://www.libarchive.org/
  summary: a static build of libarchive containing only conda-related parts
  license: BSD-2-Clause
  license_file:
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
    - static_deps_licenses/libiconv.txt    # [osx]

extra:
  recipe-maintainers:
    - msarahan
    - jjhelmus
    - isuruf
